CREATE DATABASE NARPAVI_CUSTOMER_INFO;
USE NARPAVI_CUSTOMER_INFO;

CREATE TABLE CUSTOMER_DETAILS
(
CUSTOMER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
APP_TYPE VARCHAR(20) NOT NULL,
USER_NAME VARCHAR(20),
USER_PASS VARCHAR(20),
FIRST_NAME VARCHAR(50) NOT NULL,
LAST_NAME VARCHAR(50),
DOB DATE,
ADHAR_NUM VARCHAR(50),
RATION_CARD_NUM VARCHAR(20),
DRIVING_LICENSE_NUM VARCHAR(20),
VOTER_ID_NUM VARCHAR(20),
PASSPORT_NUMBER VARCHAR(20),
PAN_ID_NUM VARCHAR(20),
EMAIL VARCHAR(50),
CONTACT_NUM VARCHAR(30) NOT NULL,
ADDRESS_STREET VARCHAR(50),
ADDRESS_VILLAGE_OR_TOWN VARCHAR(50),
ADDRESS_CITY VARCHAR(50),
ADDRESS_ZIP VARCHAR(10),
ADDRESS_STATE VARCHAR(50),
ADDRESS_COUNTRY VARCHAR(50),
VEHICLE_NUMBER VARCHAR(20),
JOB_STATUS VARCHAR(2),
CUSTOMER_DETAILS_CLOB TEXT
);


CREATE TABLE FINANCE_DETAILS
(
FINANCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FINANCE_NAME VARCHAR(100) NOT NULL,
CUSTOMER_ID INT NOT NULL,
FINANCE_OWNER_NAME VARCHAR(100),
LOAN_STATUS VARCHAR(15),
COMMENTS_ABOUT_CUSTOMER VARCHAR(500),
DELINQUENCY_AMOUNT VARCHAR(10),
REPAYMENT_TYE VARCHAR(10),
FINANCE_DETAILS_CLOB TEXT,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);

CREATE FULLTEXT INDEX CUSTOMER_DETAILS_INDEX
ON CUSTOMER_DETAILS(FIRST_NAME, LAST_NAME,ADHAR_NUM,RATION_CARD_NUM, DRIVING_LICENSE_NUM, VOTER_ID_NUM, PASSPORT_NUMBER,VEHICLE_NUMBER, EMAIL,CONTACT_NUM,ADDRESS_VILLAGE_OR_TOWN,ADDRESS_CITY,ADDRESS_ZIP,ADDRESS_STATE,ADDRESS_COUNTRY);
CREATE FULLTEXT INDEX FINANCE_DETAILS_INDEX
ON FINANCE_DETAILS(FINANCE_NAME, FINANCE_OWNER_NAME,LOAN_STATUS,COMMENTS_ABOUT_CUSTOMER,DELINQUENCY_AMOUNT,REPAYMENT_TYE);

CREATE TABLE EDU_QUALIFICATION_DETAILS
(
QUALIFICATION_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
QUALIFICATION_NAME VARCHAR(20) NOT NULL,
CUSTOMER_ID INT NOT NULL,
DEPARTMENT VARCHAR(20),
INSTITUTION_NAME VARCHAR(50),
UNIVERSITY_OR_BOARD_NAME VARCHAR(50),
CITY VARCHAR(25),
STATE VARCHAR(25),
COUNTRY VARCHAR(25),
MARKS_PERCENTAGE VARCHAR(6),
EDU_QUALIFICATION_DETAILS_CLOB TEXT,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);

CREATE FULLTEXT INDEX EDU_QUALIFICATION_DETAILS_INDEX
ON EDU_QUALIFICATION_DETAILS(QUALIFICATION_NAME, INSTITUTION_NAME,UNIVERSITY_OR_BOARD_NAME,CITY,STATE,COUNTRY,MARKS_PERCENTAGE);

CREATE TABLE WORK_EXPERIENCE_DETAILS
(
EXPERIENCE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
COMPANY_NAME VARCHAR(50) NOT NULL,
CUSTOMER_ID INT NOT NULL,
DESIGNATION VARCHAR(25) NOT NULL,
JOB_DESC VARCHAR(1000) NOT NULL,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);

CREATE FULLTEXT INDEX WORK_EXPERIENCE_DETAILS_INDEX
ON WORK_EXPERIENCE_DETAILS(COMPANY_NAME, JOB_DESC);

CREATE TABLE AWARD_DETAILS
(
AWARD_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
AWARD_NAME VARCHAR(50) NOT NULL,
INSTITUTION_NAME VARCHAR(50) NOT NULL,
CUSTOMER_ID INT NOT NULL,
AWARD_DESC VARCHAR(500) NOT NULL,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);
CREATE FULLTEXT INDEX AWARD_DETAILS_INDEX
ON AWARD_DETAILS(INSTITUTION_NAME, AWARD_DESC);

CREATE TABLE JOB_DETAILS
(
JOB_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
EMPLOYER_NAME VARCHAR(50) NOT NULL,
CUSTOMER_ID INT NOT NULL,
DESIGNATION VARCHAR(25) NOT NULL,
FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);
CREATE FULLTEXT INDEX JOB_DETAILS_INDEX
ON JOB_DETAILS(EMPLOYER_NAME, DESIGNATION);